<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Recycle_key2</name>
   <tag></tag>
   <elementGuidId>4da27814-fca1-4324-80c2-f4f84523f54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;q-app&quot;]/div/div[6]/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div/div/span/div/div</value>
   </webElementProperties>
</WebElementEntity>
