<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Recycle_search</name>
   <tag></tag>
   <elementGuidId>c1c98cdd-9651-4d02-9ad6-7888d0b58fad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;q-app&quot;]/div/div[6]/div/div[2]/div[2]/div[1]/div/div[2]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
